## Introduction 

Set of categories with no intrinsic ordering is called norminal 
For example man,women
blue,red green 

WHen set of categories has some natural ordering we call it ordinal 
For example Low, medium,High 
Young,Old

## ENcoding Nominal Categorical Features 

One hot encode is making different columns for each value using LabelBinarizer, multilabelBinarizer

In [1]:
import numpy as np 
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

In [2]:
feature=np.array([["Texas"],
                 ["California"],
                 ["Texas"],
                 ["Delware"],
                 ["Texas"]])

In [3]:
one_hot=LabelBinarizer()

In [4]:
one_hot.fit_transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
one_hot.classes_

array(['California', 'Delware', 'Texas'], dtype='<U10')

In [6]:
one_hot.inverse_transform(one_hot.transform(feature))

array(['Texas', 'California', 'Texas', 'Delware', 'Texas'], dtype='<U10')

Use pandas for one hot encode 

In [7]:
import pandas as pd 

C:\Users\16303\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\16303\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [8]:
pd.get_dummies(feature[:,0])

California  Delware  Texas
0           0        0      1
1           1        0      0
2           0        0      1
3           0        1      0
4           0        0      1

For multiple classes for each observation we use MultiLabelBinarizer()

In [9]:
multiclass_feature=[("Texas","Florida"),
                   ("California","Alabama"),
                   ("Texas","Florida"),
                   ("Delware","Florida"),
                   ("Texas","Alabma")]

In [10]:
one_hot_multiclass=MultiLabelBinarizer()

In [11]:
one_hot_multiclass.fit_transform(multiclass_feature)

array([[0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 1]])

In [12]:
one_hot_multiclass.classes_

array(['Alabama', 'Alabma', 'California', 'Delware', 'Florida', 'Texas'],
      dtype=object)

## Encoding Ordinal Categorical Features 

In [13]:
dataframe=pd.DataFrame({"Score":["Low","Low","Medium","Medium","High"]})

In [14]:
scale_mapper={"Low":1,
             "Medium":2,
             "High":3}

In [15]:
dataframe["Score"].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

## Encoding Dictionaries of Features

In [16]:
from sklearn.feature_extraction import DictVectorizer

In [17]:
data_dict=[{"Red":2,"Blue":4},
          {"Red":4,"Blue":3},
          {"Red":1,"Yellow":2},
          {"Red":2, "Yellow":2}]

In [18]:
dictvectorizer=DictVectorizer(sparse=False)

In [19]:
features=dictvectorizer.fit_transform(data_dict)

In [20]:
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

Also can use pandas Dataframe 

In [21]:
features_name=dictvectorizer.get_feature_names()
features_name

['Blue', 'Red', 'Yellow']

In [22]:
pd.DataFrame(features,columns=features_name)

Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  4.0     0.0
2   0.0  1.0     2.0
3   0.0  2.0     2.0

## Imputing Missing Class Values 

missing value for categorical features can be obatined using predict from KNN classifier

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
X=np.array([[0,2.10,1.45],
           [1,1.18,1.33],
           [0,1.22,1.27],
           [1,-0.21,-1.19]])

In [25]:
X_with_nan=np.array([[np.nan,0.87,1.31],
                    [np.nan,-0.67,-0.22]])

In [26]:
clf=KNeighborsClassifier(3,weights='distance')
trained_model=clf.fit(X[:,1:],X[:,0])

In [27]:
imputed_values=trained_model.predict(X_with_nan[:,1:])

In [28]:
X_with_imputed=np.hstack((imputed_values.reshape(-1,1),X_with_nan[:,1:]))

In [29]:
np.vstack((X_with_imputed,X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

Another way to fill missing value is with the most frequent value 

In [30]:
from sklearn.preprocessing import Imputer

In [31]:
X_complete=np.vstack((X_with_nan,X))

In [32]:
imputer=Imputer(strategy='most_frequent',axis=0)

In [33]:
imputer.fit_transform(X_complete)

array([[ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

## Handling Imbalance Class 

If our classes are highly imbalance then we solve that by getting more data otherwisehave class weigh parameters, downsampling,upsampling.

We imbalance the iris data with iris setosa of 10 instead of 50 and other 2 with 50 each that is 100 

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import numpy as np 

In [24]:
iris=load_iris()

In [25]:
features=iris.data
target=iris.target

In [26]:
features=features[40:,:]
target=target[40:]
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
target=np.where((target==0),0,1)

In [28]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Class_Weights property of randomforest let you explicity add values

In [29]:
weights={0:.9,1:0.1}

In [30]:
RandomForestClassifier(class_weight=weights)

RandomForestClassifier(bootstrap=True, class_weight={0: 0.9, 1: 0.1},
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators='warn', n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

## Class_Weights property of randomforest put balance 

In [31]:
RandomForestClassifier(class_weight="balanced")

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators='warn', n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

### We can do downsampling i.e we use just the no of observation equal to the observation of the minority class 

In [36]:
i_class0=np.where(target==0)[0]
i_class1=np.where(target==1)[0]

In [37]:
n_class0=len(i_class0)
n_class1=len(i_class1)

In [39]:
i_class1_downsampled=np.random.choice(i_class1,size=n_class0,replace=False)
len(i_class1_downsampled)

10

In [40]:
np.hstack((target[i_class0],target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
np.vstack((features[i_class0,:],features[i_class1_downsampled,:]))[0:5]

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4]])

### Upscale is just opposite of down random replacement of minority class with values

In [44]:
i_class0_upsampled=np.random.choice(i_class0,size=n_class1,replace=True)

In [45]:
np.concatenate((target[i_class0_upsampled],target[i_class1]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [46]:
np.vstack((features[i_class0_upsampled,:],features[i_class1,:]))[0:5]

array([[5. , 3.5, 1.3, 0.3],
       [5. , 3.3, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [4.4, 3.2, 1.3, 0.2]])